language: minimal

sudo: false

notifications:
  email: false

services:
  - docker

env:
  global:
    - secure: "F3elXrhy/Z5Tcaz/+XjuBH/SwosM0YVzggmG8GLs/H3U9NBnjlVcCpggQlplnlcexQ4TYaNmwkOCbDAu5Rn1S0acv3jdyAJVHVIJEafxS0A8eE5vOK/dbkTd+ODQhPlQSR4xRZwTDKuBryPHUVLn+IXUVx2HzcsoP8hwSnmBwrSZDxJzAA177yEVE4nT4XGg4VOg0zNHdUhGlkws/WaH3pkZSbSuymjqbbznkFHq4FFHeoiGYkniCS784uWMWawmr802bLjBB431TV5s1p1de9wKqNF/8CMNlR6xWdEaX80wDJTnZQyfL5Wb7AbaOSg79qTjIRwC9ab9AAJaZgXIbLYOyq63w5+Y7Gn6KST83evuMKwAYFuhSXRgDYM8ytLq+2McGFFSTHNVptzGES3Xf9Kef4+XB1Fuw5PLL0TR7ItxUUjhct2uYlcyebm/DvtL/AQlMR+xRB6rtCjS36t53SoZSdzRQRriZfao70CEZQgaQtjrBHWPV/gPZ1LhezBGDV29JXXoCcpd7ij9iITikuf8F719zZ/n0kORVykc8IKP15Z/1I0PU/KTfmaitHzUJMuL+B6SZ1SXs67EjXCIlfqCJVjcjU688JJEx2S7dE1JZ25WKk/A+2zEiwhR8HDzIvF/+iRcRKDk0UIChC1ma9Zh5ubuNHg73mnj5+lTQpw="
    # ^^ DOCKER_USERNAME
    - secure: "Oi0MjlSw+t6AA706I/yQ4VMR6ip4bn5/6IHLzbnJ8J0TBfoUtEpT3d65A4+sKQQCQolebEIw2mwn4CD5GJCfJgWEhQ30loKkel6YLkF0lYiErrsX1OVXEdYVvlUiyBNz0UNcW3kO/2hFX0uEKEA5mUh2N/9YRz1i8cNZD16A+1e+uWMFF3QURZ94eZ95bbfkGqa/Y0Um2ggI93i0Qy5mdMw39JtQGrFETRPm2T7FY0lzdovtEusADF4BUZJO40D1Tu5tPZcoTn8ZCvSZ7KoK+Qaf+SJ4CFMNOs7pLoSM00HBVqjnxuw/CSwRQ/7UGL+RAnMw7h85KZ5EPos/R2Ka1ZxAQI7VAP5+uZb2WqTj+s+Iy5BidsLPccgfd7oXCzD4lSmPFNQlMl3kb1PmB910ktEjI/fP0/mssxeOPuyqqm4vfFX3IbMEEdube9penvF20uG5VWCe82L3JtWlF7IqhL4DEt3ridwW3B8e2MtaAgE3l1Da4FRo6sFteOm0KStmhpMXET5dcrUUGLLurUOCrur9Vp/0+OJ7e2CMo0/L3CBStNB0WAUl/3up1sBjMV+lX0F+tTTwZ7IoxOYDNi99hCaRiVbdl93EAOQwpM/NTVaGBph082bUJZV9wL76toGrPSrSkTsTDKjd4A1Q+8XVh/JqxBPwrpbl/RnZvny7y+8="
    # ^^ DOCKER_PASSWORD

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - export GITHUB_SHA=$(git rev-parse --short HEAD)
  - docker build --build-arg VCS_REF=$GITHUB_SHA --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t qdrakeboo/kubectl:$(echo $GITHUB_SHA | head -c7) .

deploy:
  - provider: script
    script: docker push qdrakeboo/kubectl:$(echo $GITHUB_SHA | head -c7)
    on:
      repo: bbortt/qdrakeboo-kubectl
      branch: master
