name: Build and publish qdrakeboo-kubectl

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Build an publish Docker image
        uses: actions/checkout@v1
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: docker build \
              --build-arg VCS_REF=`git rev-parse --short HEAD` \
              --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`\
              -t bbortt/qdrakeboo-kubectl:$(echo $GITHUB_SHA | head -c7) . && \
          echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin && \
          docker push bbortt/qdrakeboo-kubectl:$(echo $GITHUB_SHA | head -c7)
